export const packs = [
  {
    name: 'Starter Pack',
    desc: 'Change to score any 1 of the tier card',
    image: 'https://apix.cubixpro.io/images/box-1.png',
    price: 30,
    buyLimit: 0,
    totalBought: 0,
    _id: 1,
    totalNFTs: 1,
  },
  {
    name: 'Bronze Pack',
    desc: '01 Legendary | 01 Super Rare | 01 Rare | 03 Common',
    image: 'https://apix.cubixpro.io/images/box-2.png',
    price: 150,
    buyLimit: 0,
    totalBought: 0,
    _id: 2,
    totalNFTs: 6,
  },
  {
    name: 'Silver Pack',
    desc: '01 Legendary | 02 Super Rare | 03 Rare | 05 Common',
    image: 'https://apix.cubixpro.io/images/box-3.png',
    price: 250,
    buyLimit: 0,
    totalBought: 0,
    _id: 3,
    totalNFTs: 11,
  },
  {
    name: 'Gold Pack',
    desc: '02 Legendary | 04 Super Rare | 09 Rare | 10 Common',
    image: 'https://apix.cubixpro.io/images/box-4.png',
    price: 500,
    buyLimit: 0,
    totalBought: 0,
    _id: 4,
    totalNFTs: 25,
  },
  {
    name: 'Platinum Pack',
    desc: '05 Legendary | 12 Super Rare | 18 Rare | 22 Common',
    image: 'https://apix.cubixpro.io/images/box-5.png',
    price: 1000,
    buyLimit: 0,
    totalBought: 0,
    _id: 5,
    totalNFTs: 57,
  },
  {
    name: 'Diamond Pack',
    desc: '15 Legendary | 31 Super Rare | 45 Rare | 60 Common',
    image: 'https://apix.cubixpro.io/images/box-6.png',
    price: 2500,
    buyLimit: 0,
    totalBought: 0,
    _id: 6,
    totalNFTs: 153,
  },
  {
    name: 'Limited Edition Pack',
    desc: '34 Legendary | 68 Super Rare | 102 Rare | 139 Common',
    image: 'https://apix.cubixpro.io/images/box-9.png',
    price: 5000,
    buyLimit: 0,
    totalBought: 0,
    _id: 7,
    totalNFTs: 343,
  },
  {
    name: 'Limited Edition Pack 02',
    desc: '34 Legendary | 68 Super Rare | 102 Rare | 139 Common',
    image: 'https://apix.cubixpro.io/images/box-9.png',
    price: 7500,
    buyLimit: 0,
    totalBought: 0,
    _id: 8,
    totalNFTs: 343,
  },
];
