export const ranks = [
  {
    name: 'Associate',
    image: '',
    color: '',
    minimumBusinessRequired: 0,
    minimumStarWithRank: '',
    matchingRatio: '',
    directSponsorBonus: 5,
    _id: 1,
    rankBonus: 0,
    directSponsorRequired: 0,
  },
  {
    name: 'Star',
    image: '',
    color: '',
    minimumBusinessRequired: 5000,
    minimumStarWithRank: '',
    matchingRatio: '',
    directSponsorBonus: 5,
    _id: 2,
    rankBonus: 125,
    directSponsorRequired: 3,
  },
  {
    name: 'Silver',
    image: '',
    color: '',
    minimumBusinessRequired: 15000,
    minimumStarWithRank: '2_2',
    matchingRatio: '1:1',
    directSponsorBonus: 5.5,
    _id: 3,
    rankBonus: 375,
    directSponsorRequired: 4,
  },
  {
    name: 'Gold',
    image: '',
    color: '',
    minimumBusinessRequired: 45000,
    minimumStarWithRank: '2_3',
    matchingRatio: '1:1',
    directSponsorBonus: 6,
    _id: 4,
    rankBonus: 1125,
    directSponsorRequired: 5,
  },
  {
    name: 'Platinum',
    image: '',
    color: '',
    minimumBusinessRequired: 105000,
    minimumStarWithRank: '2_4',
    matchingRatio: '1:1',
    directSponsorBonus: 6.5,
    _id: 5,
    rankBonus: 2625,
    directSponsorRequired: 6,
  },
  {
    name: 'Sapphire',
    image: '',
    color: '',
    minimumBusinessRequired: 225000,
    minimumStarWithRank: '2_5',
    matchingRatio: '1:1',
    directSponsorBonus: 7,
    _id: 6,
    rankBonus: 5625,
    directSponsorRequired: 7,
  },
  {
    name: 'Ruby',
    image: '',
    color: '',
    minimumBusinessRequired: 465000,
    minimumStarWithRank: '2_6',
    matchingRatio: '1:1',
    directSponsorBonus: 7.5,
    _id: 7,
    rankBonus: 11625,
    directSponsorRequired: 8,
  },
  {
    name: 'Emerald',
    image: '',
    color: '',
    minimumBusinessRequired: 945000,
    minimumStarWithRank: '3_7',
    matchingRatio: '2:1',
    directSponsorBonus: 8,
    _id: 8,
    rankBonus: 23625,
    directSponsorRequired: 9,
  },
  {
    name: 'Diamond',
    image: '',
    color: '',
    minimumBusinessRequired: 1905000,
    minimumStarWithRank: '3_8',
    matchingRatio: '2:1',
    directSponsorBonus: 8.5,
    _id: 9,
    rankBonus: 47625,
    directSponsorRequired: 10,
  },
  {
    name: 'Blue Diamond',
    image: '',
    color: '',
    minimumBusinessRequired: 3825000,
    minimumStarWithRank: '3_9',
    matchingRatio: '2:1',
    directSponsorBonus: 9,
    _id: 10,
    rankBonus: 95625,
    directSponsorRequired: 11,
  },
  {
    name: 'Green Diamond',
    image: '',
    color: '',
    minimumBusinessRequired: 7665000,
    minimumStarWithRank: '3_10',
    matchingRatio: '2:1',
    directSponsorBonus: 9.5,
    _id: 11,
    rankBonus: 191625,
    directSponsorRequired: 12,
  },
  {
    name: 'Red Diamond',
    image: '',
    color: '',
    minimumBusinessRequired: 15345000,
    minimumStarWithRank: '3_11',
    matchingRatio: '2:1',
    directSponsorBonus: 10,
    _id: 12,
    rankBonus: 383625,
    directSponsorRequired: 13,
  },
  {
    name: 'Black Diamond',
    image: '',
    color: '',
    minimumBusinessRequired: 30705000,
    minimumStarWithRank: '3_12',
    matchingRatio: '2:1',
    directSponsorBonus: 10,
    _id: 13,
    rankBonus: 767625,
    directSponsorRequired: 14,
  },
  {
    name: 'Royal Diamond',
    image: '',
    color: '',
    minimumBusinessRequired: 61425000,
    minimumStarWithRank: '3_13',
    matchingRatio: '2:1',
    directSponsorBonus: 10,
    _id: 14,
    rankBonus: 1535625,
    directSponsorRequired: 15,
  },
  {
    name: 'Crown Diamond',
    image: '',
    color: '',
    minimumBusinessRequired: 122865000,
    minimumStarWithRank: '3_14',
    matchingRatio: '2:1',
    directSponsorBonus: 10,
    _id: 15,
    rankBonus: 3071625,
    directSponsorRequired: 16,
  },
];
